version: '3.3'
services:


  frontend:
    image: mikebknd/front:latest
    volumes:
      - frontend_data:/app/result_build/


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_data:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always

    depends_on:
  
      - frontend

volumes:
  frontend_data:

