name: Run tests and Generate Coverage Report

on: [push]


jobs:
  tests_and_coverage:
    name: Run tests and Generate Coverage Report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort black pytest coverage
        pip install -r requirements.txt
    - name: Test with pytest
      run: python manage.py test --settings=foodgram.test
    - name: Generate Report
      run: coverage run -m manage test --settings=foodgram.test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1